/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.ControladorAdministracionSistema;

/**
 *
 * @author osval
 */
public class Menu extends javax.swing.JFrame {

    ControladorAdministracionSistema controladorAdministracionSistema;

    public Menu() {
        initComponents();
        this.controladorAdministracionSistema = new ControladorAdministracionSistema();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        transparenciaBtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCorteCaja = new javax.swing.JButton();
        BtnHistorial = new javax.swing.JButton();
        BtnTomarOrden = new javax.swing.JButton();
        BtnInventario = new javax.swing.JButton();
        BtnRegistrarTrabajador = new javax.swing.JButton();
        BtnRegistraPromocion = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BtnCorteCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/CorteA.png"))); // NOI18N
        BtnCorteCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCorteCaja.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/CorteA.png"))); // NOI18N
        BtnCorteCaja.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/CorteP.png"))); // NOI18N

        BtnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/HDVa.png"))); // NOI18N
        BtnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnHistorial.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/HDVa.png"))); // NOI18N
        BtnHistorial.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/HDVp.png"))); // NOI18N

        BtnTomarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/TomarOrdenA.png"))); // NOI18N
        BtnTomarOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnTomarOrden.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/TomarOrdenA.png"))); // NOI18N
        BtnTomarOrden.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/TomarOrdenP.png"))); // NOI18N
        BtnTomarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTomarOrdenActionPerformed(evt);
            }
        });

        BtnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/InventarioA.png"))); // NOI18N
        BtnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnInventario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/InventarioA.png"))); // NOI18N
        BtnInventario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/InventarioPrendido.png"))); // NOI18N
        BtnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventarioActionPerformed(evt);
            }
        });

        BtnRegistrarTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/RegisTrabajadorA.png"))); // NOI18N
        BtnRegistrarTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrarTrabajador.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/RegisTrabajadorA.png"))); // NOI18N
        BtnRegistrarTrabajador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/RegisTrabajadorP.png"))); // NOI18N

        BtnRegistraPromocion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/RegPromocionA.png"))); // NOI18N
        BtnRegistraPromocion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistraPromocion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/RegPromocionA.png"))); // NOI18N
        BtnRegistraPromocion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/RegPromocionP.png"))); // NOI18N

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/AAtrasBtn.png"))); // NOI18N
        BtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/AAtrasBtn.png"))); // NOI18N
        BtnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn/atrasBtn.png"))); // NOI18N
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BtnCorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BtnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(BtnRegistraPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(BtnRegistrarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1070, 1070, 1070)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(BtnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Fondo)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BtnTomarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(BtnCorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BtnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BtnRegistraPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(BtnRegistrarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(BtnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Fondo)
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(BtnTomarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTomarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTomarOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTomarOrdenActionPerformed

    private void BtnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventarioActionPerformed
        this.controladorAdministracionSistema.abrirInventario();
        this.setVisible(false);
    }//GEN-LAST:event_BtnInventarioActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed
    public void transparenciaBtn() {
        BtnInventario.setOpaque(false);
        BtnInventario.setContentAreaFilled(false);
        BtnInventario.setBorderPainted(false);

        BtnSalir.setOpaque(false);
        BtnSalir.setContentAreaFilled(false);
        BtnSalir.setBorderPainted(false);

        BtnHistorial.setOpaque(false);
        BtnHistorial.setContentAreaFilled(false);
        BtnHistorial.setBorderPainted(false);

        BtnCorteCaja.setOpaque(false);
        BtnCorteCaja.setContentAreaFilled(false);
        BtnCorteCaja.setBorderPainted(false);

        BtnTomarOrden.setOpaque(false);
        BtnTomarOrden.setContentAreaFilled(false);
        BtnTomarOrden.setBorderPainted(false);

        BtnRegistraPromocion.setOpaque(false);
        BtnRegistraPromocion.setContentAreaFilled(false);
        BtnRegistraPromocion.setBorderPainted(false);

        BtnRegistrarTrabajador.setOpaque(false);
        BtnRegistrarTrabajador.setContentAreaFilled(false);
        BtnRegistrarTrabajador.setBorderPainted(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCorteCaja;
    private javax.swing.JButton BtnHistorial;
    private javax.swing.JButton BtnInventario;
    private javax.swing.JButton BtnRegistraPromocion;
    private javax.swing.JButton BtnRegistrarTrabajador;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnTomarOrden;
    private javax.swing.JLabel Fondo;
    // End of variables declaration//GEN-END:variables
}
