
package presentacion;

import javax.swing.JOptionPane;
import negocio.ControladorAdministracionSistema;
import static negocio.FacadeAdministracionSistema.usuarioActivo;

public class Menu extends javax.swing.JFrame {

    ControladorAdministracionSistema controladorAdministracionSistema;

    public Menu() {
        
        initComponents();
        this.setTitle("Menu Gerencial");
        this.controladorAdministracionSistema = new ControladorAdministracionSistema();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIngresarOrden = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnCorteCaja = new javax.swing.JButton();
        btnHistorialVentas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU GERENCIAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 570, -1));

        btnIngresarOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresarOrden.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnIngresarOrden.setForeground(new java.awt.Color(51, 51, 51));
        btnIngresarOrden.setText("Ingresar Orden");
        btnIngresarOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 390, 260));

        btnInventario.setBackground(new java.awt.Color(255, 255, 255));
        btnInventario.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(51, 51, 51));
        btnInventario.setText("Administrar tu Inventario");
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 400, 260));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistro.setText("Registrar trabajador");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 400, 260));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 390, 260));

        btnCorteCaja.setBackground(new java.awt.Color(255, 255, 255));
        btnCorteCaja.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnCorteCaja.setForeground(new java.awt.Color(51, 51, 51));
        btnCorteCaja.setText("Corte Caja");
        btnCorteCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteCajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCorteCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 400, 260));

        btnHistorialVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorialVentas.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnHistorialVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorialVentas.setText("Historial de las ventas");
        btnHistorialVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorialVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 400, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        this.controladorAdministracionSistema.abrirInventario();
        this.setVisible(false);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        this.controladorAdministracionSistema.abrirRegistro();
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnIngresarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarOrdenActionPerformed
        this.controladorAdministracionSistema.abrirTomaDeOrden();
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresarOrdenActionPerformed

    private void btnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteCajaActionPerformed
        JOptionPane.showMessageDialog(this, "Caracteristica en desarrollo.");
    }//GEN-LAST:event_btnCorteCajaActionPerformed

    private void btnHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentasActionPerformed
        JOptionPane.showMessageDialog(this, "Caracteristica en desarrollo.");
    }//GEN-LAST:event_btnHistorialVentasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        usuarioActivo.setNombre("");
        usuarioActivo.setContraseña("");
        this.controladorAdministracionSistema.abrirInicioSesion();
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
    

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCorteCaja;
    private javax.swing.JButton btnHistorialVentas;
    private javax.swing.JButton btnIngresarOrden;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
